"""add name to user

Revision ID: c494cfd260b5
Revises: e6202f61069b
Create Date: 2026-06-29 22:31:12.364475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c494cfd260b5'
down_revision: Union[str, Sequence[str], None] = 'e6202f61069b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(), nullable=False))
    op.add_column('user', sa.Column('house_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'house_number')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
