"""Initial Migration

Revision ID: e6202f61069b
Revises: 
Create Date: 2026-06-23 12:15:19.300799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6202f61069b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_make',
    sa.Column('idcar_make', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('idcar_make'),
    sa.UniqueConstraint('name')
    )
    op.create_table('color',
    sa.Column('idcolor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('idcolor')
    )
    op.create_table('service',
    sa.Column('idservice', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('idservice'),
    sa.UniqueConstraint('name')
    )
    op.create_table('state',
    sa.Column('idstate', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('idstate'),
    sa.UniqueConstraint('name')
    )
    op.create_table('car_model',
    sa.Column('idcar_model', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('idcar_make', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idcar_make'], ['car_make.idcar_make'], ),
    sa.PrimaryKeyConstraint('idcar_model'),
    sa.UniqueConstraint('name')
    )
    op.create_table('city',
    sa.Column('idcity', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('idstate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idstate'], ['state.idstate'], ),
    sa.PrimaryKeyConstraint('idcity'),
    sa.UniqueConstraint('name')
    )
    op.create_table('customer',
    sa.Column('idcustomer', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idcity', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('tax_id', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('observation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['idcity'], ['city.idcity'], ),
    sa.PrimaryKeyConstraint('idcustomer')
    )
    op.create_table('employee',
    sa.Column('idemployee', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idcity', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['idcity'], ['city.idcity'], ),
    sa.PrimaryKeyConstraint('idemployee')
    )
    op.create_table('user',
    sa.Column('iduser', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('contact', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('tax_id', sa.String(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('idcity', sa.Integer(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['idcity'], ['city.idcity'], ),
    sa.PrimaryKeyConstraint('iduser')
    )
    op.create_table('vehicle',
    sa.Column('idvehicle', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idcar_model', sa.Integer(), nullable=True),
    sa.Column('idcolor', sa.Integer(), nullable=True),
    sa.Column('idcustomer', sa.Integer(), nullable=True),
    sa.Column('plate', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['idcar_model'], ['car_model.idcar_model'], ),
    sa.ForeignKeyConstraint(['idcolor'], ['color.idcolor'], ),
    sa.ForeignKeyConstraint(['idcustomer'], ['customer.idcustomer'], ),
    sa.PrimaryKeyConstraint('idvehicle'),
    sa.UniqueConstraint('plate')
    )
    op.create_table('appointments',
    sa.Column('idappointment', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idvehicle', sa.Integer(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('observation', sa.String(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'finished', 'canceled', name='appointmentstatus'), nullable=False),
    sa.ForeignKeyConstraint(['idvehicle'], ['vehicle.idvehicle'], ),
    sa.PrimaryKeyConstraint('idappointment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments')
    op.drop_table('vehicle')
    op.drop_table('user')
    op.drop_table('employee')
    op.drop_table('customer')
    op.drop_table('city')
    op.drop_table('car_model')
    op.drop_table('state')
    op.drop_table('service')
    op.drop_table('color')
    op.drop_table('car_make')
    # ### end Alembic commands ###
