from .appointments import Appointments
from .car_make import Car_make
from .car_model import Car_model
from .city import City
from .color import Color
from .customer import Customer
from .employee import Employee
from .service import Service
from .state import State
from .user import User
from .vehicle import Vehicle